Remove CI considerations from promote script

diff --git a/bin/promote b/bin/promote
--- a/bin/promote
+++ b/bin/promote
@@ -1,18 +1,12 @@
 #!/usr/bin/env bash
 
-if [ "${CI}" = "true" ]; then
-  cd "${TRAVIS_BUILD_DIR}"
-  REMOTE=https://${GITHUB_PROMOTION_AUTH}@github.com/${TRAVIS_REPO_SLUG}.git
-  SOURCE=${TRAVIS_BRANCH}
-else
-  if ! git diff-index --quiet HEAD -- ; then
-    echo "Cannot promote with a dirty working tree."
-    exit 1
-  fi
-
-  REMOTE=${2:-upstream}
-  SOURCE=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse HEAD)
+if ! git diff-index --quiet HEAD -- ; then
+  echo "Cannot promote with a dirty working tree."
+  exit 1
 fi
+
+REMOTE=${2:-upstream}
+SOURCE=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse HEAD)
 
 DEST=$1
 if [ -z "${DEST}" ]; then
@@ -26,11 +20,5 @@ set -x
 
 git checkout "${DEST}" || git checkout -b "${DEST}"
 git merge --no-ff --no-edit "${SOURCE}"
-
-{ set +x; } 2>/dev/null
-echo "+git push ${DEST}"
-git push "${REMOTE}" "${DEST}" &>/dev/null
-
-if [ ! "${CI}" = "true" ]; then
-  git checkout -
-fi
+git push "${REMOTE}" "${DEST}"
+git checkout -
